# Generated by Django 2.2.6 on 2019-11-22 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productTitle', models.CharField(max_length=50)),
                ('productDescription', models.TextField()),
                ('productRatings', models.FloatField()),
                ('productPrice', models.FloatField()),
                ('productSales', models.IntegerField()),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Category')),
            ],
        ),
    ]
