# Generated by Django 2.2.6 on 2019-11-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20191122_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productImg',
            field=models.ImageField(default=0, upload_to='Products'),
            preserve_default=False,
        ),
    ]
