# Generated by Django 2.2.6 on 2019-11-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_remove_products_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productImg',
            field=models.ImageField(default='default.png', upload_to='Products'),
        ),
    ]
